$schema: http://json-schema.org/draft-07/schema
type: object
required:
  - type
properties:
  type:
    const: character
    default: character
  version:
    const: 1
    default: 1
  config:
    type: object
    properties:
      ui:
        type: object
        properties:
          rolling:
            type: boolean
          attributeOrder:
            type: array
            items:
              type: string
          poolOrder:
            type: array
            items:
              type: string
      equipment:
        type: object
        properties:
          locations:
            type: array
            items:
              type: string
      rulesets:
        type: object
        properties:
          useMultiplicativeModifiers:
            type: boolean
            default: false
          useKnowingYourOwnStrength:
            type: boolean
            default: false
          useReducedSwingDamage:
            type: boolean
            default: false
          useNoSchoolGrognardReducedSwingDamage:
            type: boolean
            defualt: false
      attributes:
        type: object
        patternProperties:
          .:
            $ref: attribute.json
      locations:
        type: object
        patternProperties:
          .:
            $ref: hitLocation.json
    default: "@require ./static/characterConfig.json"
  profile:
    type: object
    properties: {}
    default: {}
  pointTotal:
    type: integer
    default: 150
  hitLocationDamage:
    type: object
    patternProperties:
      .:
        type: integer
    default: {}
  attributeLevels:
    type: object
    patternProperties:
      .:
        type: object
        properties:
          mod:
            type: integer
    default: {}
example:
  config:
  profile:
    name: Samantha
    nickName: Sammy
  pointTotal: 250
  hitLocationDamage:
    left arm: 5
    right leg: 7
  attributeLevels:
    strength:
      mod: 2
      current: 12
