$schema: http://json-schema.org/draft-07/schema
$id: http://valorsheet/systems/gurps/equipment.yaml
type: object
require:
  - type
properties:
  type:
    const: equipment
    default: equipment
    map:
      gcs: type
  version:
    const: 1
    default: 1
    map:
      gcs: version
  name:
    type: string
    map:
      gcs:
        key: description
  weight:
    type: number
    default: 1
    map:
      gcs: weight
  value:
    type: number
    default: 0
    map:
      gcs: value
  location:
    type: string
    default: carried
  quantity:
    type: integer
    default: 1
    map:
      gcs: quantity
  uses:
    type: integer
    default: 0
    map:
      gcs: uses
  maxUses:
    type: integer
    default: 0
    map:
      gcs: max_uses
  ignoreForSkills:
    type: boolean
    default: false
    map:
      gcs: ignore_for_skills
example:
  name: Reinforced Leather Satchel
  weight: 2.15
  value: 40.25
  location: carried
  quantity: 1
  uses: null
  maxUses: null
  ignoreForSkills: false
