$schema: http://json-schema.org/draft-07/schema
$id: http://valorsheet/systems/gurps/hitLocation.yaml
type: object
properties:
  isGroup:
    type: boolean
  subLocations:
    type: array
    items:
      type: string
  has:
    type: array
    items:
      type: string
  hitRange:
    type: array
    items:
      type: number
  hitModifier:
    type: number
  naturalArmor:
    type: number
  crippleDivisor:
    type: number
