$schema: http://json-schema.org/draft-07/schema
type: object
allOf:
  - $ref: definitions.json#/weapon
properties:
  type:
    const: melee weapon
    default: melee weapon
  version:
    const: 1
    default: 1
  parryBonus:
    type: integer
  blockBonus:
    type: integer
  reach:
    type: string
