$schema: http://json-schema.org/draft-07/schema
type: object
allOf:
  - $ref: definitions.json#/definitions/weapon
properties:
  type:
    const: ranged weapon
    default: ranged weapon
  version:
    const: 1
    default: 1
  accuracy:
    type: string
  range:
    type: string
  rateOfFire:
    type: string
  shots:
    type: string
  recoil:
    type: integer
  bulk:
    type: string
