$schema: http://json-schema.org/draft-07/schema
$id: http://valorsheet/systems/gurps/skill.yaml
type: object
properties:
  type:
    const: skill
    default: skill
    map:
      gcs: type
  version:
    const: 1
    default: 1
    map:
      gcs: version
  name:
    type: string
    map:
      gcs: name
  specialization:
    type: string
    map:
      gcs: specialization
  techLevel:
    type: string
    map:
      gcs: tech_level
  points:
    type: integer
    default: 1
    map:
      gcs: points
  difficulty:
    enum:
      - E
      - A
      - H
      - VH
      - WC
    default: A
    map:
      gcs:
        key: difficulty
        transfrom: return sourceValue.split('/')[1]
        revert: const {difficulty, signature} = sourceObject; return `${signature}/${difficulty}`
  signature:
    type: string
    map:
      gcs:
        key: difficulty
        transform: return sourceValue.split('/')[0]
  defaults:
    type: array
    items:
      $ref: definitions.yaml#/default
  mod:
    type: integer
    default: 0
  encumbrancePenaltyMultiple:
    type: number
    default: 0