import "dexie-observable";
import { Dexie } from 'dexie';
import { IDatabaseChange } from 'dexie-observable/api';
import { State, KeyFunc } from "rxdeep";
import { Subject } from 'rxjs';
export declare const db: Dexie;
export declare const changes$: Subject<IDatabaseChange[]>;
export declare function fetchRecord<T extends Record<string, any>>(tableName: string, key: string): Promise<State<T>>;
export declare function stamp(value: any): any;
export declare function isFresh(a: any, b: any): boolean;
export declare function update(table: any, key: any, value: any): Promise<number>;
export declare function fetchTable<T>(tableName: string, keyfunc?: KeyFunc<T>): Promise<import("rxdeep").KeyedState<T>>;
